# Generated by asset_id_files.py

AGON_ENERGY_CONTROLLER_MREA = 0x02FC3717
AGON_MAP_STATION_MREA = 0x845C85A7
AGON_TEMPLE_MREA = 0x75FC9AAE
BATTLEGROUND_MREA = 0xEA79522C
BIOENERGY_PRODUCTION_MREA = 0x13470DA8
BIOSTORAGE_ACCESS_MREA = 0xDEEB1668
BIOSTORAGE_STATION_MREA = 0x80896CE9
BITTER_WELL_MREA = 0x04F1C1D8
CENTRAL_MINING_STATION_MREA = 0xF5A6D972
CENTRAL_STATION_ACCESS_MREA = 0xFE69E0C3
COMMAND_CENTER_MREA = 0x31C25557
COMMAND_CENTER_ACCESS_MREA = 0x708387F9
CONTROLLER_ACCESS_MREA = 0xBF5399C0
CROSSROADS_MREA = 0x8E23DB3F
DARK_AGON_ENERGY_CONTROLLER_MREA = 0xB7DD4006
DARK_AGON_TEMPLE_MREA = 0x7575048A
DARK_AGON_TEMPLE_ACCESS_MREA = 0x2103C8AE
DARK_CONTROLLER_ACCESS_MREA = 0xA2F347D1
DARK_OASIS_MREA = 0x99FB957F
DARK_TRANSIT_STATION_MREA = 0xD73ECD68
DOOMED_ENTRY_MREA = 0xA49F8A6D
DOUBLE_PATH_MREA = 0x7FEF433B
DUELLING_RANGE_MREA = 0x3F5CDF39
FEEDING_PIT_MREA = 0x075A76EB
FEEDING_PIT_ACCESS_MREA = 0xE035C0A5
HALL_OF_STAIRS_MREA = 0x6D164780
ING_CACHE_1_MREA = 0x52962FB6
ING_CACHE_2_MREA = 0x9318F076
ING_CACHE_3_MREA = 0xBA23E5F5
ING_CACHE_4_MREA = 0xC5C7C9D3
JUDGMENT_PIT_MREA = 0x6B77F9BD
JUNCTION_SITE_MREA = 0x1608C563
MAIN_ENERGY_CONTROLLER_MREA = 0xD92890C3
MAIN_REACTOR_MREA = 0xCCD9F39E
MINE_SHAFT_MREA = 0xD7A15431
MINING_PLAZA_MREA = 0x427FAD9A
MINING_STATION_A_MREA = 0xE3BEF27F
MINING_STATION_ACCESS_MREA = 0x8D7A7F8C
MINING_STATION_B_MREA = 0xDB7B2CED
OASIS_ACCESS_MREA = 0xF2CCC41E
PHAZON_SITE_MREA = 0x200EF5E7
PLAZA_ACCESS_MREA = 0xADF88927
PORTAL_ACCESS_MREA = 0x89D246FD
PORTAL_ACCESS_A_MREA = 0x2312EE1D
PORTAL_SITE_MREA = 0xBF7F572C
PORTAL_TERMINAL_MREA = 0x2BCD44A7
SAND_CACHE_MREA = 0xF4B1F727
SAND_PROCESSING_MREA = 0xA4B2CB7E
SANDCANYON_MREA = 0xE5B72628
SAVE_STATION_1_MREA = 0x5A154E2E
SAVE_STATION_2_MREA = 0xAC204F8B
SAVE_STATION_3_MREA = 0x0279F7EF
SAVE_STATION_A_MREA = 0x50017152
SAVE_STATION_C_MREA = 0xB979562C
SECURITY_STATION_A_MREA = 0xF723A29A
SECURITY_STATION_B_MREA = 0x0ADA5AEF
STORAGE_A_MREA = 0x10323944
STORAGE_B_MREA = 0x96A64BEA
STORAGE_C_MREA = 0x5DFA984F
STORAGE_D_MREA = 0x40FFA8F7
TEMPLE_ACCESS_MREA = 0x2A58AC44
TRANSIT_STATION_MREA = 0x79C9C5A0
TRANSPORT_CENTER_MREA = 0x4BDFB7B9
TRANSPORT_TO_SANCTUARY_FORTRESS_MREA = 0xC68B5B51
TRANSPORT_TO_TEMPLE_GROUNDS_MREA = 0x57CE3A52
TRANSPORT_TO_TORVUS_BOG_MREA = 0xA74EC002
TRIAL_GROUNDS_MREA = 0x86C1AB37
TRIAL_TUNNEL_MREA = 0x48E44EF6
VENTILATION_AREA_A_MREA = 0x84303DD5
VENTILATION_AREA_B_MREA = 0x594B330B
WARRIORS_WALK_MREA = 0x33FACC15
WATERING_HOLE_MREA = 0x9B2B4246

NAME_TO_ID = {
    "Agon Energy Controller": 0x02FC3717,
    "Agon Map Station": 0x845C85A7,
    "Agon Temple": 0x75FC9AAE,
    "Battleground": 0xEA79522C,
    "Bioenergy Production": 0x13470DA8,
    "Biostorage Access": 0xDEEB1668,
    "Biostorage Station": 0x80896CE9,
    "Bitter Well": 0x04F1C1D8,
    "Central Mining Station": 0xF5A6D972,
    "Central Station Access": 0xFE69E0C3,
    "Command Center": 0x31C25557,
    "Command Center Access": 0x708387F9,
    "Controller Access": 0xBF5399C0,
    "Crossroads": 0x8E23DB3F,
    "Dark Agon Energy Controller": 0xB7DD4006,
    "Dark Agon Temple": 0x7575048A,
    "Dark Agon Temple Access": 0x2103C8AE,
    "Dark Controller Access": 0xA2F347D1,
    "Dark Oasis": 0x99FB957F,
    "Dark Transit Station": 0xD73ECD68,
    "Doomed Entry": 0xA49F8A6D,
    "Double Path": 0x7FEF433B,
    "Duelling Range": 0x3F5CDF39,
    "Feeding Pit": 0x075A76EB,
    "Feeding Pit Access": 0xE035C0A5,
    "Hall of Stairs": 0x6D164780,
    "Ing Cache 1": 0x52962FB6,
    "Ing Cache 2": 0x9318F076,
    "Ing Cache 3": 0xBA23E5F5,
    "Ing Cache 4": 0xC5C7C9D3,
    "Judgment Pit": 0x6B77F9BD,
    "Junction Site": 0x1608C563,
    "Main Energy Controller": 0xD92890C3,
    "Main Reactor": 0xCCD9F39E,
    "Mine Shaft": 0xD7A15431,
    "Mining Plaza": 0x427FAD9A,
    "Mining Station A": 0xE3BEF27F,
    "Mining Station Access": 0x8D7A7F8C,
    "Mining Station B": 0xDB7B2CED,
    "Oasis Access": 0xF2CCC41E,
    "Phazon Site": 0x200EF5E7,
    "Plaza Access": 0xADF88927,
    "Portal Access": 0x89D246FD,
    "Portal Access A": 0x2312EE1D,
    "Portal Site": 0xBF7F572C,
    "Portal Terminal": 0x2BCD44A7,
    "Sand Cache": 0xF4B1F727,
    "Sand Processing": 0xA4B2CB7E,
    "Sandcanyon": 0xE5B72628,
    "Save Station 1": 0x5A154E2E,
    "Save Station 2": 0xAC204F8B,
    "Save Station 3": 0x0279F7EF,
    "Save Station A": 0x50017152,
    "Save Station C": 0xB979562C,
    "Security Station A": 0xF723A29A,
    "Security Station B": 0x0ADA5AEF,
    "Storage A": 0x10323944,
    "Storage B": 0x96A64BEA,
    "Storage C": 0x5DFA984F,
    "Storage D": 0x40FFA8F7,
    "Temple Access": 0x2A58AC44,
    "Transit Station": 0x79C9C5A0,
    "Transport Center": 0x4BDFB7B9,
    "Transport to Sanctuary Fortress": 0xC68B5B51,
    "Transport to Temple Grounds": 0x57CE3A52,
    "Transport to Torvus Bog": 0xA74EC002,
    "Trial Grounds": 0x86C1AB37,
    "Trial Tunnel": 0x48E44EF6,
    "Ventilation Area A": 0x84303DD5,
    "Ventilation Area B": 0x594B330B,
    "Warrior's Walk": 0x33FACC15,
    "Watering Hole": 0x9B2B4246,
}

DOCK_NAMES = {
    "Agon Energy Controller": {
        "South": 0,
        "North1 (to 08 Copy)": 1,
    },
    "Agon Map Station": {
        "South": 0,
    },
    "Agon Temple": {
        "West": 0,
        "North": 1,
        "East": 2,
        "South": 3,
    },
    "Battleground": {
        "East_Lower": 0,
        "East_Upper": 1,
        "West": 2,
    },
    "Bioenergy Production": {
        "South": 0,
        "North": 1,
        "East": 2,
    },
    "Biostorage Access": {
        "South": 0,
        "North": 1,
    },
    "Biostorage Station": {
        "East": 0,
        "North": 1,
        "West": 2,
    },
    "Bitter Well": {
        "South": 0,
        "North": 1,
    },
    "Central Mining Station": {
        "East_Lower": 0,
        "East_Upper": 1,
        "West": 2,
    },
    "Central Station Access": {
        "West": 0,
        "East": 1,
    },
    "Command Center": {
        "WestLowerDoor": 0,
        "South": 1,
        "North": 2,
        "NorthObservation": 3,
        "WestUpperDoor": 4,
        "WestMorphballTunnel": 5,
        "VirtualNorth": 6,
    },
    "Command Center Access": {
        "EastLowerDoor": 0,
        "EastUpperDoor": 1,
        "EastMorphballTunnel": 2,
        "West_Upper": 3,
        "West_Lower": 4,
    },
    "Controller Access": {
        "North": 0,
        "South1": 1,
    },
    "Crossroads": {
        "West": 0,
        "East": 1,
        "South": 2,
        "VirtualNorth": 3,
    },
    "Dark Agon Energy Controller": {
        "South": 0,
        "North1": 1,
    },
    "Dark Agon Temple": {
        "West": 0,
        "North": 1,
        "East": 2,
        "South": 3,
    },
    "Dark Agon Temple Access": {
        "North": 0,
        "South": 1,
    },
    "Dark Controller Access": {
        "North": 0,
        "South1": 1,
    },
    "Dark Oasis": {
        "East_TopSouth": 0,
        "West_TopSouth": 1,
        "West_TopNorth": 2,
        "South1": 3,
        "VirtualEast": 4,
    },
    "Dark Transit Station": {
        "East": 0,
        "South": 1,
    },
    "Doomed Entry": {
        "WestLowerDoor": 0,
        "South": 1,
        "NorthObservation": 2,
        "WestUpperDoor": 3,
        "VirtualNorth": 4,
    },
    "Double Path": {
        "EastLowerDoor": 0,
        "EastUpperDoor": 1,
        "EastMorphballTunnel": 2,
        "West_Upper": 3,
        "West_Lower": 4,
    },
    "Duelling Range": {
        "North": 0,
        "South": 1,
        "West": 2,
        "East": 3,
        "VirtualDock": 4,
    },
    "Feeding Pit": {
        "East": 0,
        "North": 1,
        "West": 2,
    },
    "Feeding Pit Access": {
        "South": 0,
        "North": 1,
    },
    "Hall of Stairs": {
        "East": 0,
        "West": 1,
    },
    "Ing Cache 1": {
        "East": 0,
    },
    "Ing Cache 2": {
        "West": 0,
    },
    "Ing Cache 3": {
        "East": 0,
    },
    "Ing Cache 4": {
        "West": 0,
        "East": 1,
    },
    "Judgment Pit": {
        "North": 0,
        "East1": 1,
        "South_save": 2,
        "West1": 3,
        "South1": 4,
    },
    "Junction Site": {
        "East": 0,
        "West": 1,
    },
    "Main Energy Controller": {
        "SouthLight1": 0,
        "VirtualNorth": 1,
        "North1 (to 00 Sand Generator)": 2,
    },
    "Main Reactor": {
        "East_TopSouth": 0,
        "West_TopSouth": 1,
        "West_TopNorth": 2,
        "Docks_Docks_Docks_South": 3,
        "VirtualEast": 4,
    },
    "Mine Shaft": {
        "West": 0,
        "East": 1,
    },
    "Mining Plaza": {
        "NorthMap": 0,
        "North": 1,
        "South": 2,
        "West": 3,
        "East1": 4,
        "VirtualDock": 5,
    },
    "Mining Station A": {
        "North": 0,
        "East1": 1,
        "South_save": 2,
        "West1": 3,
        "South1": 4,
    },
    "Mining Station Access": {
        "East": 0,
        "West": 1,
    },
    "Mining Station B": {
        "Docks_SouthLower": 0,
        "East": 1,
        "West": 2,
        "VirtualNorth": 3,
    },
    "Oasis Access": {
        "South": 0,
        "South_Observation": 1,
        "North": 2,
    },
    "Phazon Site": {
        "South": 0,
        "North": 1,
        "East": 2,
    },
    "Plaza Access": {
        "West": 0,
        "East": 1,
    },
    "Portal Access": {
        "South": 0,
        "North": 1,
    },
    "Portal Access A": {
        "South": 0,
        "North": 1,
    },
    "Portal Site": {
        "North": 0,
        "West": 1,
        "VirtualNorth1": 2,
    },
    "Portal Terminal": {
        "North": 0,
        "West": 1,
        "VirtualNorth1": 2,
    },
    "Sand Cache": {
        "North": 0,
    },
    "Sand Processing": {
        "East": 0,
        "West": 1,
    },
    "Sandcanyon": {
        "West": 0,
        "East": 1,
    },
    "Save Station 1": {
        "North": 0,
    },
    "Save Station 2": {
        "North": 0,
        "East": 1,
    },
    "Save Station 3": {
        "South": 0,
        "West": 1,
    },
    "Save Station A": {
        "North": 0,
        "East": 1,
    },
    "Save Station C": {
        "South": 0,
        "West": 1,
    },
    "Security Station A": {
        "West": 0,
        "North": 1,
    },
    "Security Station B": {
        "South": 0,
        "South_Observation": 1,
        "North": 2,
    },
    "Storage A": {
        "North": 0,
    },
    "Storage B": {
        "East": 0,
    },
    "Storage C": {
        "West": 0,
    },
    "Storage D": {
        "East": 0,
    },
    "Temple Access": {
        "North": 0,
        "South": 1,
    },
    "Transit Station": {
        "East": 0,
        "South": 1,
    },
    "Transport Center": {
        "West": 0,
        "East": 1,
        "South": 2,
        "VirtualNorth": 3,
    },
    "Transport to Sanctuary Fortress": {
        "Dock - South": 0,
    },
    "Transport to Temple Grounds": {
        "East": 0,
    },
    "Transport to Torvus Bog": {
        "Dock - North": 0,
    },
    "Trial Grounds": {
        "Docks_SouthLower": 0,
        "East": 1,
        "West": 2,
        "VirtualNorth": 3,
    },
    "Trial Tunnel": {
        "West": 0,
        "East": 1,
    },
    "Ventilation Area A": {
        "docks_North": 0,
        "docks_docks_East": 1,
        "docks_West": 2,
    },
    "Ventilation Area B": {
        "South": 0,
        "North": 1,
    },
    "Warrior's Walk": {
        "West": 0,
        "East": 1,
    },
    "Watering Hole": {
        "West": 0,
        "North": 1,
    },
}
