# Generated by asset_id_files.py

CONTROLLER_TRANSPORT_MREA = 0x11E50BC6
MAIN_ENERGY_CONTROLLER_MREA = 0x02A01334
SANCTUM_MREA = 0xD7C3B839
SANCTUM_ACCESS_MREA = 0xCBAD889B
SKY_TEMPLE_ENERGY_CONTROLLER_MREA = 0x7B4AFA6F
TEMPLE_SANCTUARY_MREA = 0xA2CB7E32
TEMPLE_TRANSPORT_A_MREA = 0x185B40F0
TEMPLE_TRANSPORT_B_MREA = 0x8F01B104
TEMPLE_TRANSPORT_C_MREA = 0x9860CBB0
TRANSPORT_A_ACCESS_MREA = 0xE79AAFAE
TRANSPORT_B_ACCESS_MREA = 0xFEB7BD27
TRANSPORT_C_ACCESS_MREA = 0x1A4DDCC0

NAME_TO_ID = {
    "Controller Transport": 0x11E50BC6,
    "Main Energy Controller": 0x02A01334,
    "Sanctum": 0xD7C3B839,
    "Sanctum Access": 0xCBAD889B,
    "Sky Temple Energy Controller": 0x7B4AFA6F,
    "Temple Sanctuary": 0xA2CB7E32,
    "Temple Transport A": 0x185B40F0,
    "Temple Transport B": 0x8F01B104,
    "Temple Transport C": 0x9860CBB0,
    "Transport A Access": 0xE79AAFAE,
    "Transport B Access": 0xFEB7BD27,
    "Transport C Access": 0x1A4DDCC0,
}

DOCK_NAMES = {
    "Controller Transport": {
        "NorthBottom": 0,
        "NorthTop": 1,
    },
    "Main Energy Controller": {
        "SouthLight": 0,
        "VirtualNorth": 1,
        "North1": 2,
    },
    "Sanctum": {
        "SouthDark": 0,
    },
    "Sanctum Access": {
        "DarkTop": 0,
        "Darkbottom": 1,
    },
    "Sky Temple Energy Controller": {
        "SouthLight": 0,
        "VirtualNorth": 1,
    },
    "Temple Sanctuary": {
        "North": 0,
        "West": 1,
        "South": 2,
        "East": 3,
    },
    "Temple Transport A": {
        "South": 0,
    },
    "Temple Transport B": {
        "West": 0,
    },
    "Temple Transport C": {
        "East": 0,
    },
    "Transport A Access": {
        "North": 0,
        "South": 1,
    },
    "Transport B Access": {
        "West": 0,
        "East": 1,
    },
    "Transport C Access": {
        "East": 0,
        "West": 1,
    },
}
