# Generated by asset_id_files.py

SCANDUMMY_MREA = 0x131C3388
ABANDONED_BASE_MREA = 0xC6F4E0C2
ACCURSED_LAKE_MREA = 0x9FD196DF
AGON_TRANSPORT_ACCESS_MREA = 0xA391C9AB
BASE_ACCESS_MREA = 0x686F5A1B
COLLAPSED_TUNNEL_MREA = 0x5B92D146
COMMAND_CHAMBER_MREA = 0xD627000B
COMMUNICATION_AREA_MREA = 0x635E8DA1
DEFILED_SHRINE_MREA = 0x16E116B4
DYNAMO_CHAMBER_MREA = 0xB4C067A7
FORTRESS_TRANSPORT_ACCESS_MREA = 0x70E5E6DD
GFMC_COMPOUND_MREA = 0x57757AD5
GATEWAY_ACCESS_MREA = 0x84324C98
GRAND_WINDCHAMBER_MREA = 0xAD70917D
HALL_OF_EYES_MREA = 0x476BA84C
HALL_OF_HONORED_DEAD_MREA = 0xB8B34634
HIVE_ACCESS_TUNNEL_MREA = 0xB1140C24
HIVE_CHAMBER_A_MREA = 0x50B372A5
HIVE_CHAMBER_B_MREA = 0x1D7BD3AE
HIVE_CHAMBER_C_MREA = 0xFB843824
HIVE_SAVE_STATION_MREA = 0x1461DC2F
HIVE_STORAGE_MREA = 0x6367D577
HIVE_TRANSPORT_AREA_MREA = 0x941F873A
HIVE_TUNNEL_MREA = 0x1582EC4A
INDUSTRIAL_SITE_MREA = 0x62AC8AC4
ING_RELIQUARY_MREA = 0x749E82E3
ING_WINDCHAMBER_MREA = 0xCDEF2BF1
LAKE_ACCESS_MREA = 0x688AB8AE
LANDING_SITE_MREA = 0x62B0D67D
MEETING_GROUNDS_MREA = 0x9B5EFA75
PATH_OF_EYES_MREA = 0xEE4732BE
PATH_OF_HONOR_MREA = 0x7B4D31DB
PHAZON_GROUNDS_MREA = 0x645EF243
PHAZON_PIT_MREA = 0x1E332000
PLAIN_OF_DARK_WORSHIP_MREA = 0x0405EBA4
PORTAL_SITE_MREA = 0xDA37FF97
PROFANE_PATH_MREA = 0x64E640D6
RELIQUARY_ACCESS_MREA = 0x8540CAD4
RELIQUARY_GROUNDS_MREA = 0xFC8FC0A4
SACRED_BRIDGE_MREA = 0xBABCDB22
SACRED_PATH_MREA = 0xC23CFFBD
SERVICE_ACCESS_MREA = 0x9FB7503C
SHRINE_ACCESS_MREA = 0x1F1D07DF
SKY_TEMPLE_GATEWAY_MREA = 0x87D35EE4
STORAGE_CAVERN_A_MREA = 0x3800CF82
STORAGE_CAVERN_B_MREA = 0xBE94BD2C
TEMPLE_ASSEMBLY_SITE_MREA = 0x4B4E5911
TEMPLE_TRANSPORT_A_MREA = 0x503A0640
TEMPLE_TRANSPORT_B_MREA = 0x4CC37F4A
TEMPLE_TRANSPORT_C_MREA = 0xADED752E
TORVUS_TRANSPORT_ACCESS_MREA = 0xA8391EAD
TRANSPORT_TO_AGON_WASTES_MREA = 0x62FF94EE
TRANSPORT_TO_SANCTUARY_FORTRESS_MREA = 0xCDF7686B
TRANSPORT_TO_TORVUS_BOG_MREA = 0xAC32F338
TROOPER_SECURITY_STATION_MREA = 0x55EE6DC3
WAR_RITUAL_GROUNDS_MREA = 0xAA77EAAD
WINDCHAMBER_GATEWAY_MREA = 0x75318D5E
WINDCHAMBER_TUNNEL_MREA = 0x9A633BBF
GAME_END_PART1_MREA = 0x1ED8D8B1
GAME_END_PART2_MREA = 0x984CAA1F
GAME_END_PART3_MREA = 0x531079BA
GAME_END_PART4_MREA = 0x4E154902
GAME_END_PART5_MREA = 0x85499AA7

NAME_TO_ID = {
    "00_scandummy": 0x131C3388,
    "Abandoned Base": 0xC6F4E0C2,
    "Accursed Lake": 0x9FD196DF,
    "Agon Transport Access": 0xA391C9AB,
    "Base Access": 0x686F5A1B,
    "Collapsed Tunnel": 0x5B92D146,
    "Command Chamber": 0xD627000B,
    "Communication Area": 0x635E8DA1,
    "Defiled Shrine": 0x16E116B4,
    "Dynamo Chamber": 0xB4C067A7,
    "Fortress Transport Access": 0x70E5E6DD,
    "GFMC Compound": 0x57757AD5,
    "Gateway Access": 0x84324C98,
    "Grand Windchamber": 0xAD70917D,
    "Hall of Eyes": 0x476BA84C,
    "Hall of Honored Dead": 0xB8B34634,
    "Hive Access Tunnel": 0xB1140C24,
    "Hive Chamber A": 0x50B372A5,
    "Hive Chamber B": 0x1D7BD3AE,
    "Hive Chamber C": 0xFB843824,
    "Hive Save Station": 0x1461DC2F,
    "Hive Storage": 0x6367D577,
    "Hive Transport Area": 0x941F873A,
    "Hive Tunnel": 0x1582EC4A,
    "Industrial Site": 0x62AC8AC4,
    "Ing Reliquary": 0x749E82E3,
    "Ing Windchamber": 0xCDEF2BF1,
    "Lake Access": 0x688AB8AE,
    "Landing Site": 0x62B0D67D,
    "Meeting Grounds": 0x9B5EFA75,
    "Path of Eyes": 0xEE4732BE,
    "Path of Honor": 0x7B4D31DB,
    "Phazon Grounds": 0x645EF243,
    "Phazon Pit": 0x1E332000,
    "Plain of Dark Worship": 0x0405EBA4,
    "Portal Site": 0xDA37FF97,
    "Profane Path": 0x64E640D6,
    "Reliquary Access": 0x8540CAD4,
    "Reliquary Grounds": 0xFC8FC0A4,
    "Sacred Bridge": 0xBABCDB22,
    "Sacred Path": 0xC23CFFBD,
    "Service Access": 0x9FB7503C,
    "Shrine Access": 0x1F1D07DF,
    "Sky Temple Gateway": 0x87D35EE4,
    "Storage Cavern A": 0x3800CF82,
    "Storage Cavern B": 0xBE94BD2C,
    "Temple Assembly Site": 0x4B4E5911,
    "Temple Transport A": 0x503A0640,
    "Temple Transport B": 0x4CC37F4A,
    "Temple Transport C": 0xADED752E,
    "Torvus Transport Access": 0xA8391EAD,
    "Transport to Agon Wastes": 0x62FF94EE,
    "Transport to Sanctuary Fortress": 0xCDF7686B,
    "Transport to Torvus Bog": 0xAC32F338,
    "Trooper Security Station": 0x55EE6DC3,
    "War Ritual Grounds": 0xAA77EAAD,
    "Windchamber Gateway": 0x75318D5E,
    "Windchamber Tunnel": 0x9A633BBF,
    "game_end_part1": 0x1ED8D8B1,
    "game_end_part2": 0x984CAA1F,
    "game_end_part3": 0x531079BA,
    "game_end_part4": 0x4E154902,
    "game_end_part5": 0x85499AA7,
}

DOCK_NAMES = {
    "00_scandummy": {
        "VirtualNorth": 0,
    },
    "Abandoned Base": {
        "East": 0,
        "North": 1,
        "South": 2,
        "VirtualNorth": 3,
    },
    "Accursed Lake": {
        "East": 0,
        "North": 1,
        "West": 2,
    },
    "Agon Transport Access": {
        "West": 0,
        "South": 1,
    },
    "Base Access": {
        "Docks_VirtualNorth": 0,
        "South": 1,
        "West": 2,
    },
    "Collapsed Tunnel": {
        "A__South": 0,
        "A__North1": 1,
    },
    "Command Chamber": {
        "West2": 0,
        "East": 1,
    },
    "Communication Area": {
        "South1": 0,
        "North": 1,
        "South11": 2,
    },
    "Defiled Shrine": {
        "North": 0,
        "East1": 1,
        "VirtualWest": 2,
    },
    "Dynamo Chamber": {
        "North": 0,
        "South": 1,
    },
    "Fortress Transport Access": {
        "West": 0,
        "South": 1,
    },
    "GFMC Compound": {
        "East": 0,
        "North": 1,
        "WestTop": 2,
        "West": 3,
    },
    "Gateway Access": {
        "West": 0,
        "WestUpper": 1,
        "NorthUpper": 2,
        "North": 3,
    },
    "Grand Windchamber": {
        "North": 0,
        "West": 1,
        "VirtualNorth1": 2,
    },
    "Hall of Eyes": {
        "Docks_VirtualNorth": 0,
        "South": 1,
        "West": 2,
    },
    "Hall of Honored Dead": {
        "South_Morphball": 0,
        "South": 1,
        "VirtualNorth": 2,
    },
    "Hive Access Tunnel": {
        "East": 0,
        "West": 1,
        "Floor": 2,
    },
    "Hive Chamber A": {
        "Ceiling": 0,
        "East": 1,
    },
    "Hive Chamber B": {
        "South": 0,
        "North": 1,
        "VirtualDock": 2,
    },
    "Hive Chamber C": {
        "blue_01_Temple_Hive_1_4_West_BigDoor": 0,
        "South": 1,
        "North1": 2,
    },
    "Hive Save Station": {
        "South": 0,
    },
    "Hive Storage": {
        "West": 0,
        "North1": 1,
    },
    "Hive Transport Area": {
        "East_Upper": 0,
        "group35_blue_01_Temple_Hive_1_4_East_BigDoor": 1,
        "West": 2,
    },
    "Hive Tunnel": {
        "West": 0,
        "East1": 1,
    },
    "Industrial Site": {
        "East": 0,
        "North": 1,
        "West": 2,
    },
    "Ing Reliquary": {
        "North_Top": 0,
    },
    "Ing Windchamber": {
        "North": 0,
        "West": 1,
        "VirtualNorth1": 2,
    },
    "Lake Access": {
        "A__South": 0,
        "A__North1": 1,
    },
    "Landing Site": {
        "North": 0,
        "East1": 1,
    },
    "Meeting Grounds": {
        "North": 0,
        "East1": 1,
        "EastTop": 2,
        "EastBottom": 3,
    },
    "Path of Eyes": {
        "East": 0,
        "North": 1,
        "South": 2,
        "VirtualNorth": 3,
    },
    "Path of Honor": {
        "West": 0,
        "WestUpper": 1,
        "NorthUpper": 2,
        "North": 3,
    },
    "Phazon Grounds": {
        "East": 0,
        "North": 1,
        "WestTop": 2,
        "West": 3,
    },
    "Phazon Pit": {
        "East": 0,
        "South": 1,
    },
    "Plain of Dark Worship": {
        "South": 0,
        "North": 1,
        "South1": 2,
        "VirtualNorth": 3,
    },
    "Portal Site": {
        "South": 0,
        "North": 1,
        "VirtualDock": 2,
    },
    "Profane Path": {
        "North": 0,
        "VirtualNorth1": 1,
    },
    "Reliquary Access": {
        "South": 0,
        "West": 1,
    },
    "Reliquary Grounds": {
        "South_Top": 0,
        "North": 1,
        "South_Bottom": 2,
    },
    "Sacred Bridge": {
        "East": 0,
        "South": 1,
    },
    "Sacred Path": {
        "South1": 0,
        "North": 1,
        "VirtualNorth1": 2,
    },
    "Service Access": {
        "South": 0,
        "East": 1,
        "West": 2,
        "East1": 3,
        "West11": 4,
    },
    "Shrine Access": {
        "South": 0,
        "East": 1,
        "West": 2,
        "East1": 3,
        "West11": 4,
    },
    "Sky Temple Gateway": {
        "South": 0,
        "VirtualNorth": 1,
        "Cinema_Dock": 2,
    },
    "Storage Cavern A": {
        "North_Top": 0,
    },
    "Storage Cavern B": {
        "North": 0,
    },
    "Temple Assembly Site": {
        "South": 0,
        "North": 1,
        "West": 2,
        "South1": 3,
        "VirtualNorth": 4,
    },
    "Temple Transport A": {
        "North": 0,
    },
    "Temple Transport B": {
        "East": 0,
    },
    "Temple Transport C": {
        "blue_0M_Temple_hall_West": 0,
    },
    "Torvus Transport Access": {
        "North": 0,
        "South": 1,
    },
    "Transport to Agon Wastes": {
        "Dock - North": 0,
    },
    "Transport to Sanctuary Fortress": {
        "East": 0,
    },
    "Transport to Torvus Bog": {
        "North": 0,
    },
    "Trooper Security Station": {
        "blue_0D_Temple_hall_South": 0,
        "blue_0D_Temple_hall_West": 1,
    },
    "War Ritual Grounds": {
        "North": 0,
        "EastTop": 1,
        "EastBottom": 2,
    },
    "Windchamber Gateway": {
        "East": 0,
        "South": 1,
    },
    "Windchamber Tunnel": {
        "South": 0,
        "East": 1,
    },
    "game_end_part1": {
        "South_Morphball": 0,
        "South": 1,
        "VirtualNorth": 2,
        "cinema_light2": 3,
        "cinema_light1": 4,
    },
    "game_end_part2": {
        "SouthLight1": 0,
        "VirtualNorth": 1,
        "North1": 2,
        "cinema_dock1": 3,
        "cinema_dock2": 4,
    },
    "game_end_part3": {
        "North": 0,
        "East1": 1,
        "cinema_dock": 2,
        "SPACEROOM": 3,
    },
    "game_end_part4": {
        "cinema_dock": 0,
        "North": 1,
    },
    "game_end_part5": {
        "cinema_dock": 0,
    },
}
