name: Linting

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  ty:
    runs-on: ubuntu-latest
    name: Wheel

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.2"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: build
        run: uv sync --frozen --group dev

      - name: ty
        run: uv run ty check src
